USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS IDENTIFIER($PROJECT_ROLE);

GRANT ROLE IDENTIFIER($PROJECT_ROLE) TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($PROJECT_WH)
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 5400
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Causal Chain Strategy Simulator - 90 min auto_suspend';

GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($PROJECT_ROLE);

CREATE DATABASE IF NOT EXISTS IDENTIFIER($PROJECT_DB);
GRANT OWNERSHIP ON DATABASE IDENTIFIER($PROJECT_DB) TO ROLE IDENTIFIER($PROJECT_ROLE);

USE ROLE IDENTIFIER($PROJECT_ROLE);
USE DATABASE IDENTIFIER($PROJECT_DB);
DROP SCHEMA IF EXISTS PUBLIC;
