CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;
CREATE SCHEMA IF NOT EXISTS INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS APPS;
CREATE SCHEMA IF NOT EXISTS STAGES;
