CREATE OR REPLACE TABLE ANALYTICS.FACT_PERFORMANCE_SNAPSHOT (
    SNAPSHOT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PERFORMANCE_MONTH DATE NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    STRATEGY_MODE VARCHAR(20) NOT NULL, -- GROWTH, MARGIN, CASH
    
    -- Service Metrics
    OTIF_PCT FLOAT,
    FILL_RATE_PCT FLOAT,
    NET_SALES_GROWTH_PCT FLOAT,
    LEAD_TIME_DAYS FLOAT,
    ORDER_FLEXIBILITY_SCORE FLOAT,
    FORECAST_MAPE_PCT FLOAT,
    FORECAST_BIAS_PCT FLOAT,
    NPI_COUNT NUMBER,
    
    -- Cost Metrics  
    GROSS_MARGIN_PCT FLOAT,
    EBITDA_MARGIN_PCT FLOAT,
    COGS_USD FLOAT,
    SGA_USD FLOAT,
    OEE_PCT FLOAT,
    FIRST_PASS_YIELD_PCT FLOAT,
    PURCHASING_PRICE_INDEX FLOAT,
    
    -- Cash Metrics
    ROCE_PCT FLOAT,
    FREE_CASH_FLOW_USD FLOAT,
    CASH_CONVERSION_CYCLE_DAYS FLOAT,
    DIOH_DAYS FLOAT,
    DSO_DAYS FLOAT,
    DPO_DAYS FLOAT,
    ASSET_TURNS FLOAT,
    
    -- Inventory Values (USD)
    CYCLE_STOCK_VALUE FLOAT,
    SAFETY_STOCK_VALUE FLOAT,
    PIPELINE_STOCK_VALUE FLOAT,
    ANTICIPATION_STOCK_VALUE FLOAT,
    STRATEGIC_STOCK_VALUE FLOAT,
    TOTAL_INVENTORY_VALUE FLOAT,
    
    -- Financial Bridge
    NOPAT_USD FLOAT,
    WORKING_CAPITAL_DELTA_USD FLOAT,
    FIXED_ASSET_DELTA_USD FLOAT,
    CAPITAL_EMPLOYED_USD FLOAT,
    EVA_USD FLOAT,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ANALYTICS.DIM_INVENTORY_STRUCTURE (
    INVENTORY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    INVENTORY_TYPE VARCHAR(30) NOT NULL, -- CYCLE, SAFETY, PIPELINE, ANTICIPATION, STRATEGIC
    DESCRIPTION VARCHAR(500),
    ECONOMIC_DRIVER VARCHAR(200),
    TYPICAL_RANGE_PCT_LOW FLOAT,
    TYPICAL_RANGE_PCT_HIGH FLOAT,
    REDUCTION_STRATEGY VARCHAR(500)
);

CREATE OR REPLACE TABLE ANALYTICS.SCENARIO_CONTROL (
    SCENARIO_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    STRATEGY_MODE VARCHAR(20) NOT NULL, -- GROWTH, MARGIN, CASH
    SHOCK_EVENT VARCHAR(100), -- NULL, SUPPLY_DISRUPTION, PORT_STRIKE, etc.
    
    -- Delta Modifiers (multipliers to apply)
    SERVICE_WEIGHT FLOAT DEFAULT 1.0,
    COST_WEIGHT FLOAT DEFAULT 1.0,
    CASH_WEIGHT FLOAT DEFAULT 1.0,
    
    -- Metric Adjustments
    OTIF_DELTA_PCT FLOAT DEFAULT 0,
    LEAD_TIME_DELTA_DAYS FLOAT DEFAULT 0,
    SAFETY_STOCK_DELTA_PCT FLOAT DEFAULT 0,
    PIPELINE_STOCK_DELTA_PCT FLOAT DEFAULT 0,
    ROCE_DELTA_PCT FLOAT DEFAULT 0,
    FCF_DELTA_PCT FLOAT DEFAULT 0,
    
    PERMISSIBLE_RED VARCHAR(50),
    MANDATORY_GREEN VARCHAR(50),
    ECONOMIC_BET VARCHAR(200)
);

CREATE OR REPLACE TABLE ANALYTICS.ML_PREDICTION_REGISTRY (
    PREDICTION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    MODEL_NAME VARCHAR(50) NOT NULL, -- PROPHET, XGBOOST
    MODEL_VERSION VARCHAR(20),
    TARGET_VARIABLE VARCHAR(50) NOT NULL,
    FEATURE_SET VARIANT,
    TRAINING_DATE DATE,
    VALIDATION_METRICS VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE CONSUMPTION.PREDICTIVE_BRIDGE (
    BRIDGE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PERFORMANCE_MONTH DATE NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    SCENARIO_ID NUMBER REFERENCES ANALYTICS.SCENARIO_CONTROL(SCENARIO_ID),
    
    -- Pre-computed ML Predictions
    PREDICTED_FCF_USD FLOAT,
    PREDICTED_ROCE_PCT FLOAT,
    PREDICTED_SAFETY_STOCK_USD FLOAT,
    PREDICTED_PIPELINE_STOCK_USD FLOAT,
    
    -- Causal Trace Links
    LEAD_TIME_IMPACT_FCF FLOAT,
    FORECAST_ERROR_IMPACT_SAFETY FLOAT,
    BATCH_SIZE_IMPACT_CYCLE FLOAT,
    
    -- Confidence Intervals
    FCF_LOWER_BOUND FLOAT,
    FCF_UPPER_BOUND FLOAT,
    ROCE_LOWER_BOUND FLOAT,
    ROCE_UPPER_BOUND FLOAT,
    
    MODEL_SOURCE VARCHAR(50),
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QBR_DOCUMENTS (
    DOC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DOC_NAME VARCHAR(200) NOT NULL,
    DOC_TYPE VARCHAR(50), -- QBR, RISK_ASSESSMENT
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    CONTENT_TEXT TEXT,
    CONTENT_EMBEDDING VECTOR(FLOAT, 768),
    UPLOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INTELLIGENCE.CAUSAL_TRACE_DEFINITIONS (
    TRACE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_METRIC VARCHAR(50) NOT NULL,
    TARGET_METRIC VARCHAR(50) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(30), -- POSITIVE, NEGATIVE, NEUTRAL
    CAUSAL_WEIGHT FLOAT,
    DESCRIPTION VARCHAR(500),
    EXAMPLE_SCENARIO VARCHAR(500)
);
