-- =============================================================================
-- RAW LAYER: Landing zone with source metadata columns
-- =============================================================================

CREATE OR REPLACE TABLE RAW.PERFORMANCE_SNAPSHOT_STAGE (
    SNAPSHOT_ID VARCHAR(50),
    PERFORMANCE_MONTH VARCHAR(50),
    REGION VARCHAR(50),
    STRATEGY_MODE VARCHAR(20),
    OTIF_PCT VARCHAR(20),
    FILL_RATE_PCT VARCHAR(20),
    NET_SALES_GROWTH_PCT VARCHAR(20),
    LEAD_TIME_DAYS VARCHAR(20),
    ORDER_FLEXIBILITY_SCORE VARCHAR(20),
    FORECAST_MAPE_PCT VARCHAR(20),
    FORECAST_BIAS_PCT VARCHAR(20),
    NPI_COUNT VARCHAR(20),
    GROSS_MARGIN_PCT VARCHAR(20),
    EBITDA_MARGIN_PCT VARCHAR(20),
    COGS_USD VARCHAR(20),
    SGA_USD VARCHAR(20),
    OEE_PCT VARCHAR(20),
    FIRST_PASS_YIELD_PCT VARCHAR(20),
    PURCHASING_PRICE_INDEX VARCHAR(20),
    ROCE_PCT VARCHAR(20),
    FREE_CASH_FLOW_USD VARCHAR(20),
    CASH_CONVERSION_CYCLE_DAYS VARCHAR(20),
    DIOH_DAYS VARCHAR(20),
    DSO_DAYS VARCHAR(20),
    DPO_DAYS VARCHAR(20),
    ASSET_TURNS VARCHAR(20),
    CYCLE_STOCK_VALUE VARCHAR(20),
    SAFETY_STOCK_VALUE VARCHAR(20),
    PIPELINE_STOCK_VALUE VARCHAR(20),
    ANTICIPATION_STOCK_VALUE VARCHAR(20),
    STRATEGIC_STOCK_VALUE VARCHAR(20),
    TOTAL_INVENTORY_VALUE VARCHAR(20),
    NOPAT_USD VARCHAR(20),
    WORKING_CAPITAL_DELTA_USD VARCHAR(20),
    FIXED_ASSET_DELTA_USD VARCHAR(20),
    CAPITAL_EMPLOYED_USD VARCHAR(20),
    EVA_USD VARCHAR(20),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.INVENTORY_STRUCTURE_STAGE (
    INVENTORY_ID VARCHAR(50),
    INVENTORY_TYPE VARCHAR(30),
    DESCRIPTION VARCHAR(500),
    ECONOMIC_DRIVER VARCHAR(200),
    TYPICAL_RANGE_PCT_LOW VARCHAR(20),
    TYPICAL_RANGE_PCT_HIGH VARCHAR(20),
    REDUCTION_STRATEGY VARCHAR(500),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SCENARIO_CONTROL_STAGE (
    STRATEGY_MODE VARCHAR(20),
    SHOCK_EVENT VARCHAR(100),
    SERVICE_WEIGHT VARCHAR(20),
    COST_WEIGHT VARCHAR(20),
    CASH_WEIGHT VARCHAR(20),
    OTIF_DELTA_PCT VARCHAR(20),
    LEAD_TIME_DELTA_DAYS VARCHAR(20),
    SAFETY_STOCK_DELTA_PCT VARCHAR(20),
    PIPELINE_STOCK_DELTA_PCT VARCHAR(20),
    ROCE_DELTA_PCT VARCHAR(20),
    FCF_DELTA_PCT VARCHAR(20),
    PERMISSIBLE_RED VARCHAR(50),
    MANDATORY_GREEN VARCHAR(50),
    ECONOMIC_BET VARCHAR(200),
    SCENARIO_ID VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PREDICTIVE_BRIDGE_STAGE (
    BRIDGE_ID VARCHAR(50),
    PERFORMANCE_MONTH VARCHAR(50),
    REGION VARCHAR(50),
    SCENARIO_ID VARCHAR(50),
    PREDICTED_FCF_USD VARCHAR(20),
    PREDICTED_ROCE_PCT VARCHAR(20),
    PREDICTED_SAFETY_STOCK_USD VARCHAR(20),
    PREDICTED_PIPELINE_STOCK_USD VARCHAR(20),
    LEAD_TIME_IMPACT_FCF VARCHAR(20),
    FORECAST_ERROR_IMPACT_SAFETY VARCHAR(20),
    BATCH_SIZE_IMPACT_CYCLE VARCHAR(20),
    FCF_LOWER_BOUND VARCHAR(20),
    FCF_UPPER_BOUND VARCHAR(20),
    ROCE_LOWER_BOUND VARCHAR(20),
    ROCE_UPPER_BOUND VARCHAR(20),
    MODEL_SOURCE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ML_MODEL_REGISTRY_STAGE (
    MODEL_ID VARCHAR(50),
    MODEL_NAME VARCHAR(50),
    MODEL_VERSION VARCHAR(20),
    TARGET_VARIABLE VARCHAR(50),
    FEATURE_SET VARCHAR(2000),
    TRAINING_DATE VARCHAR(50),
    VALIDATION_METRICS VARCHAR(2000),
    IS_ACTIVE VARCHAR(10),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CAUSAL_TRACE_STAGE (
    SOURCE_METRIC VARCHAR(50),
    TARGET_METRIC VARCHAR(50),
    RELATIONSHIP_TYPE VARCHAR(30),
    CAUSAL_WEIGHT VARCHAR(20),
    DESCRIPTION VARCHAR(500),
    EXAMPLE_SCENARIO VARCHAR(500),
    TRACE_ID VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(500) DEFAULT METADATA$FILENAME,
    _SOURCE_FILE_ROW_NUMBER NUMBER DEFAULT METADATA$FILE_ROW_NUMBER,
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QBR_DOCUMENTS (
    DOC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DOC_NAME VARCHAR(200) NOT NULL,
    DOC_TYPE VARCHAR(50),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    CONTENT_TEXT TEXT,
    CONTENT_EMBEDDING VECTOR(FLOAT, 768),
    _SOURCE_FILE_NAME VARCHAR(500),
    _LOADED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- ATOMIC LAYER: Normalized enterprise model with audit columns
-- Reference tables and scenario configuration only (no aggregates)
-- =============================================================================

CREATE OR REPLACE TABLE ATOMIC.DIM_INVENTORY_STRUCTURE (
    INVENTORY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    INVENTORY_TYPE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(500),
    ECONOMIC_DRIVER VARCHAR(200),
    TYPICAL_RANGE_PCT_LOW FLOAT,
    TYPICAL_RANGE_PCT_HIGH FLOAT,
    REDUCTION_STRATEGY VARCHAR(500),
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

COMMENT ON TABLE ATOMIC.DIM_INVENTORY_STRUCTURE IS 'Inventory type definitions and economic drivers for decomposition analysis';

CREATE OR REPLACE TABLE ATOMIC.SCENARIO_CONTROL (
    SCENARIO_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    STRATEGY_MODE VARCHAR(20) NOT NULL,
    SHOCK_EVENT VARCHAR(100),
    SERVICE_WEIGHT FLOAT DEFAULT 1.0,
    COST_WEIGHT FLOAT DEFAULT 1.0,
    CASH_WEIGHT FLOAT DEFAULT 1.0,
    OTIF_DELTA_PCT FLOAT DEFAULT 0,
    LEAD_TIME_DELTA_DAYS FLOAT DEFAULT 0,
    SAFETY_STOCK_DELTA_PCT FLOAT DEFAULT 0,
    PIPELINE_STOCK_DELTA_PCT FLOAT DEFAULT 0,
    ROCE_DELTA_PCT FLOAT DEFAULT 0,
    FCF_DELTA_PCT FLOAT DEFAULT 0,
    PERMISSIBLE_RED VARCHAR(50),
    MANDATORY_GREEN VARCHAR(50),
    ECONOMIC_BET VARCHAR(200),
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

COMMENT ON TABLE ATOMIC.SCENARIO_CONTROL IS 'Strategy scenario parameters and shock event modifiers for what-if analysis';

CREATE OR REPLACE TABLE ATOMIC.CAUSAL_TRACE_DEFINITION (
    TRACE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_METRIC VARCHAR(50) NOT NULL,
    TARGET_METRIC VARCHAR(50) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(30),
    CAUSAL_WEIGHT FLOAT,
    DESCRIPTION VARCHAR(500),
    EXAMPLE_SCENARIO VARCHAR(500),
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

COMMENT ON TABLE ATOMIC.CAUSAL_TRACE_DEFINITION IS 'Causal relationships between supply chain metrics for root cause analysis';

CREATE OR REPLACE TABLE ATOMIC.ML_MODEL_REGISTRY (
    MODEL_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    MODEL_NAME VARCHAR(50) NOT NULL,
    MODEL_VERSION VARCHAR(20),
    TARGET_VARIABLE VARCHAR(50) NOT NULL,
    FEATURE_SET VARIANT,
    TRAINING_DATE DATE,
    VALIDATION_METRICS VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

COMMENT ON TABLE ATOMIC.ML_MODEL_REGISTRY IS 'Registry of ML models used for predictive analytics (catalog of trained models)';

-- =============================================================================
-- STRATEGY_SIMULATOR (DATA MART): Consumer-facing tables for the app
-- Denormalized aggregates and pre-computed predictions
-- =============================================================================

CREATE OR REPLACE TABLE STRATEGY_SIMULATOR.FACT_PERFORMANCE_SNAPSHOT (
    SNAPSHOT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PERFORMANCE_MONTH DATE NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    STRATEGY_MODE VARCHAR(20) NOT NULL,
    OTIF_PCT FLOAT,
    FILL_RATE_PCT FLOAT,
    NET_SALES_GROWTH_PCT FLOAT,
    LEAD_TIME_DAYS FLOAT,
    ORDER_FLEXIBILITY_SCORE FLOAT,
    FORECAST_MAPE_PCT FLOAT,
    FORECAST_BIAS_PCT FLOAT,
    NPI_COUNT NUMBER,
    GROSS_MARGIN_PCT FLOAT,
    EBITDA_MARGIN_PCT FLOAT,
    COGS_USD FLOAT,
    SGA_USD FLOAT,
    OEE_PCT FLOAT,
    FIRST_PASS_YIELD_PCT FLOAT,
    PURCHASING_PRICE_INDEX FLOAT,
    ROCE_PCT FLOAT,
    FREE_CASH_FLOW_USD FLOAT,
    CASH_CONVERSION_CYCLE_DAYS FLOAT,
    DIOH_DAYS FLOAT,
    DSO_DAYS FLOAT,
    DPO_DAYS FLOAT,
    ASSET_TURNS FLOAT,
    CYCLE_STOCK_VALUE FLOAT,
    SAFETY_STOCK_VALUE FLOAT,
    PIPELINE_STOCK_VALUE FLOAT,
    ANTICIPATION_STOCK_VALUE FLOAT,
    STRATEGIC_STOCK_VALUE FLOAT,
    TOTAL_INVENTORY_VALUE FLOAT,
    NOPAT_USD FLOAT,
    WORKING_CAPITAL_DELTA_USD FLOAT,
    FIXED_ASSET_DELTA_USD FLOAT,
    CAPITAL_EMPLOYED_USD FLOAT,
    EVA_USD FLOAT,
    REFRESHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE STRATEGY_SIMULATOR.FACT_PERFORMANCE_SNAPSHOT IS 'Denormalized monthly supply chain performance metrics for Strategy Simulator dashboard';

CREATE OR REPLACE TABLE STRATEGY_SIMULATOR.PREDICTIVE_BRIDGE (
    BRIDGE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PERFORMANCE_MONTH DATE NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    SCENARIO_ID NUMBER REFERENCES ATOMIC.SCENARIO_CONTROL(SCENARIO_ID),
    PREDICTED_FCF_USD FLOAT,
    PREDICTED_ROCE_PCT FLOAT,
    PREDICTED_SAFETY_STOCK_USD FLOAT,
    PREDICTED_PIPELINE_STOCK_USD FLOAT,
    LEAD_TIME_IMPACT_FCF FLOAT,
    FORECAST_ERROR_IMPACT_SAFETY FLOAT,
    BATCH_SIZE_IMPACT_CYCLE FLOAT,
    FCF_LOWER_BOUND FLOAT,
    FCF_UPPER_BOUND FLOAT,
    ROCE_LOWER_BOUND FLOAT,
    ROCE_UPPER_BOUND FLOAT,
    MODEL_SOURCE VARCHAR(50),
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE STRATEGY_SIMULATOR.PREDICTIVE_BRIDGE IS 'Pre-computed ML predictions for what-if scenarios in Strategy Simulator';

CREATE OR REPLACE VIEW STRATEGY_SIMULATOR.V_PERFORMANCE_SUMMARY AS
SELECT 
    f.PERFORMANCE_MONTH,
    f.REGION,
    f.STRATEGY_MODE,
    ROUND(f.OTIF_PCT, 2) AS OTIF_PCT,
    ROUND(f.GROSS_MARGIN_PCT, 2) AS GROSS_MARGIN_PCT,
    ROUND(f.ROCE_PCT, 2) AS ROCE_PCT,
    ROUND(f.FREE_CASH_FLOW_USD, 2) AS FREE_CASH_FLOW_USD,
    ROUND(f.CYCLE_STOCK_VALUE, 2) AS CYCLE_STOCK_VALUE,
    ROUND(f.SAFETY_STOCK_VALUE, 2) AS SAFETY_STOCK_VALUE,
    ROUND(f.PIPELINE_STOCK_VALUE, 2) AS PIPELINE_STOCK_VALUE,
    ROUND(f.ANTICIPATION_STOCK_VALUE, 2) AS ANTICIPATION_STOCK_VALUE,
    ROUND(f.STRATEGIC_STOCK_VALUE, 2) AS STRATEGIC_STOCK_VALUE,
    ROUND(f.TOTAL_INVENTORY_VALUE, 2) AS TOTAL_INVENTORY_VALUE
FROM STRATEGY_SIMULATOR.FACT_PERFORMANCE_SNAPSHOT f;

COMMENT ON VIEW STRATEGY_SIMULATOR.V_PERFORMANCE_SUMMARY IS 'Consumer-facing view of performance metrics with standardized rounding';

CREATE OR REPLACE VIEW STRATEGY_SIMULATOR.V_CAUSAL_TRACES AS
SELECT 
    c.TRACE_ID,
    c.SOURCE_METRIC,
    c.TARGET_METRIC,
    c.RELATIONSHIP_TYPE,
    c.CAUSAL_WEIGHT,
    c.DESCRIPTION,
    c.EXAMPLE_SCENARIO
FROM ATOMIC.CAUSAL_TRACE_DEFINITION c
ORDER BY c.CAUSAL_WEIGHT DESC;

COMMENT ON VIEW STRATEGY_SIMULATOR.V_CAUSAL_TRACES IS 'Consumer-facing view of causal trace definitions for Sankey visualization';
