CREATE OR REPLACE STAGE STAGES.DATA_STAGE;

PUT file://data/synthetic/fact_performance_snapshot.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/dim_inventory_structure.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/scenario_control.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/predictive_bridge.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/ml_prediction_registry.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/causal_trace_definitions.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/qbr_documents.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

COPY INTO ANALYTICS.FACT_PERFORMANCE_SNAPSHOT (
    SNAPSHOT_ID, PERFORMANCE_MONTH, REGION, STRATEGY_MODE,
    OTIF_PCT, FILL_RATE_PCT, NET_SALES_GROWTH_PCT, LEAD_TIME_DAYS,
    ORDER_FLEXIBILITY_SCORE, FORECAST_MAPE_PCT, FORECAST_BIAS_PCT, NPI_COUNT,
    GROSS_MARGIN_PCT, EBITDA_MARGIN_PCT, COGS_USD, SGA_USD,
    OEE_PCT, FIRST_PASS_YIELD_PCT, PURCHASING_PRICE_INDEX,
    ROCE_PCT, FREE_CASH_FLOW_USD, CASH_CONVERSION_CYCLE_DAYS,
    DIOH_DAYS, DSO_DAYS, DPO_DAYS, ASSET_TURNS,
    CYCLE_STOCK_VALUE, SAFETY_STOCK_VALUE, PIPELINE_STOCK_VALUE,
    ANTICIPATION_STOCK_VALUE, STRATEGIC_STOCK_VALUE, TOTAL_INVENTORY_VALUE,
    NOPAT_USD, WORKING_CAPITAL_DELTA_USD, FIXED_ASSET_DELTA_USD,
    CAPITAL_EMPLOYED_USD, EVA_USD
)
FROM @STAGES.DATA_STAGE/fact_performance_snapshot.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO ANALYTICS.DIM_INVENTORY_STRUCTURE (
    INVENTORY_ID, INVENTORY_TYPE, DESCRIPTION, ECONOMIC_DRIVER,
    TYPICAL_RANGE_PCT_LOW, TYPICAL_RANGE_PCT_HIGH, REDUCTION_STRATEGY
)
FROM @STAGES.DATA_STAGE/dim_inventory_structure.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO ANALYTICS.SCENARIO_CONTROL (
    STRATEGY_MODE, SHOCK_EVENT, SERVICE_WEIGHT, COST_WEIGHT, CASH_WEIGHT,
    OTIF_DELTA_PCT, LEAD_TIME_DELTA_DAYS, SAFETY_STOCK_DELTA_PCT, PIPELINE_STOCK_DELTA_PCT,
    ROCE_DELTA_PCT, FCF_DELTA_PCT, PERMISSIBLE_RED, MANDATORY_GREEN, ECONOMIC_BET, SCENARIO_ID
)
FROM @STAGES.DATA_STAGE/scenario_control.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = (''));

COPY INTO CONSUMPTION.PREDICTIVE_BRIDGE (
    BRIDGE_ID, PERFORMANCE_MONTH, REGION, SCENARIO_ID,
    PREDICTED_FCF_USD, PREDICTED_ROCE_PCT, PREDICTED_SAFETY_STOCK_USD, PREDICTED_PIPELINE_STOCK_USD,
    LEAD_TIME_IMPACT_FCF, FORECAST_ERROR_IMPACT_SAFETY, BATCH_SIZE_IMPACT_CYCLE,
    FCF_LOWER_BOUND, FCF_UPPER_BOUND, ROCE_LOWER_BOUND, ROCE_UPPER_BOUND, MODEL_SOURCE
)
FROM @STAGES.DATA_STAGE/predictive_bridge.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO ANALYTICS.ML_PREDICTION_REGISTRY (
    PREDICTION_ID, MODEL_NAME, MODEL_VERSION, TARGET_VARIABLE,
    FEATURE_SET, TRAINING_DATE, VALIDATION_METRICS, IS_ACTIVE
)
FROM @STAGES.DATA_STAGE/ml_prediction_registry.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO INTELLIGENCE.CAUSAL_TRACE_DEFINITIONS (
    SOURCE_METRIC, TARGET_METRIC, RELATIONSHIP_TYPE,
    CAUSAL_WEIGHT, DESCRIPTION, EXAMPLE_SCENARIO, TRACE_ID
)
FROM @STAGES.DATA_STAGE/causal_trace_definitions.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.QBR_DOCUMENTS (
    DOC_ID, DOC_NAME, DOC_TYPE, QUARTER, YEAR, CONTENT_TEXT
)
FROM @STAGES.DATA_STAGE/qbr_documents.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
