-- =============================================================================
-- STAGE SETUP
-- =============================================================================
CREATE OR REPLACE STAGE STAGES.DATA_STAGE;

-- =============================================================================
-- STEP 1: Upload CSV files to stage
-- =============================================================================
PUT file://data/synthetic/fact_performance_snapshot.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/dim_inventory_structure.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/scenario_control.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/predictive_bridge.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/ml_prediction_registry.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/causal_trace_definitions.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://data/synthetic/qbr_documents.csv @STAGES.DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- =============================================================================
-- STEP 2: Load into RAW staging tables (VARCHAR, with metadata)
-- =============================================================================

COPY INTO RAW.PERFORMANCE_SNAPSHOT_STAGE (
    SNAPSHOT_ID, PERFORMANCE_MONTH, REGION, STRATEGY_MODE,
    OTIF_PCT, FILL_RATE_PCT, NET_SALES_GROWTH_PCT, LEAD_TIME_DAYS,
    ORDER_FLEXIBILITY_SCORE, FORECAST_MAPE_PCT, FORECAST_BIAS_PCT, NPI_COUNT,
    GROSS_MARGIN_PCT, EBITDA_MARGIN_PCT, COGS_USD, SGA_USD,
    OEE_PCT, FIRST_PASS_YIELD_PCT, PURCHASING_PRICE_INDEX,
    ROCE_PCT, FREE_CASH_FLOW_USD, CASH_CONVERSION_CYCLE_DAYS,
    DIOH_DAYS, DSO_DAYS, DPO_DAYS, ASSET_TURNS,
    CYCLE_STOCK_VALUE, SAFETY_STOCK_VALUE, PIPELINE_STOCK_VALUE,
    ANTICIPATION_STOCK_VALUE, STRATEGIC_STOCK_VALUE, TOTAL_INVENTORY_VALUE,
    NOPAT_USD, WORKING_CAPITAL_DELTA_USD, FIXED_ASSET_DELTA_USD,
    CAPITAL_EMPLOYED_USD, EVA_USD
)
FROM @STAGES.DATA_STAGE/fact_performance_snapshot.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.INVENTORY_STRUCTURE_STAGE (
    INVENTORY_ID, INVENTORY_TYPE, DESCRIPTION, ECONOMIC_DRIVER,
    TYPICAL_RANGE_PCT_LOW, TYPICAL_RANGE_PCT_HIGH, REDUCTION_STRATEGY
)
FROM @STAGES.DATA_STAGE/dim_inventory_structure.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.SCENARIO_CONTROL_STAGE (
    STRATEGY_MODE, SHOCK_EVENT, SERVICE_WEIGHT, COST_WEIGHT, CASH_WEIGHT,
    OTIF_DELTA_PCT, LEAD_TIME_DELTA_DAYS, SAFETY_STOCK_DELTA_PCT, PIPELINE_STOCK_DELTA_PCT,
    ROCE_DELTA_PCT, FCF_DELTA_PCT, PERMISSIBLE_RED, MANDATORY_GREEN, ECONOMIC_BET, SCENARIO_ID
)
FROM @STAGES.DATA_STAGE/scenario_control.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = (''));

COPY INTO RAW.PREDICTIVE_BRIDGE_STAGE (
    BRIDGE_ID, PERFORMANCE_MONTH, REGION, SCENARIO_ID,
    PREDICTED_FCF_USD, PREDICTED_ROCE_PCT, PREDICTED_SAFETY_STOCK_USD, PREDICTED_PIPELINE_STOCK_USD,
    LEAD_TIME_IMPACT_FCF, FORECAST_ERROR_IMPACT_SAFETY, BATCH_SIZE_IMPACT_CYCLE,
    FCF_LOWER_BOUND, FCF_UPPER_BOUND, ROCE_LOWER_BOUND, ROCE_UPPER_BOUND, MODEL_SOURCE
)
FROM @STAGES.DATA_STAGE/predictive_bridge.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.ML_MODEL_REGISTRY_STAGE (
    MODEL_ID, MODEL_NAME, MODEL_VERSION, TARGET_VARIABLE,
    FEATURE_SET, TRAINING_DATE, VALIDATION_METRICS, IS_ACTIVE
)
FROM @STAGES.DATA_STAGE/ml_prediction_registry.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.CAUSAL_TRACE_STAGE (
    SOURCE_METRIC, TARGET_METRIC, RELATIONSHIP_TYPE,
    CAUSAL_WEIGHT, DESCRIPTION, EXAMPLE_SCENARIO, TRACE_ID
)
FROM @STAGES.DATA_STAGE/causal_trace_definitions.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO RAW.QBR_DOCUMENTS (
    DOC_ID, DOC_NAME, DOC_TYPE, QUARTER, YEAR, CONTENT_TEXT
)
FROM @STAGES.DATA_STAGE/qbr_documents.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- =============================================================================
-- STEP 3: Transform from RAW to ATOMIC (reference/config tables only)
-- =============================================================================

INSERT INTO ATOMIC.DIM_INVENTORY_STRUCTURE (
    INVENTORY_TYPE, DESCRIPTION, ECONOMIC_DRIVER,
    TYPICAL_RANGE_PCT_LOW, TYPICAL_RANGE_PCT_HIGH, REDUCTION_STRATEGY
)
SELECT 
    INVENTORY_TYPE,
    DESCRIPTION,
    ECONOMIC_DRIVER,
    TRY_TO_DOUBLE(TYPICAL_RANGE_PCT_LOW),
    TRY_TO_DOUBLE(TYPICAL_RANGE_PCT_HIGH),
    REDUCTION_STRATEGY
FROM RAW.INVENTORY_STRUCTURE_STAGE;

INSERT INTO ATOMIC.SCENARIO_CONTROL (
    STRATEGY_MODE, SHOCK_EVENT, SERVICE_WEIGHT, COST_WEIGHT, CASH_WEIGHT,
    OTIF_DELTA_PCT, LEAD_TIME_DELTA_DAYS, SAFETY_STOCK_DELTA_PCT, PIPELINE_STOCK_DELTA_PCT,
    ROCE_DELTA_PCT, FCF_DELTA_PCT, PERMISSIBLE_RED, MANDATORY_GREEN, ECONOMIC_BET
)
SELECT 
    STRATEGY_MODE,
    NULLIF(SHOCK_EVENT, ''),
    TRY_TO_DOUBLE(SERVICE_WEIGHT),
    TRY_TO_DOUBLE(COST_WEIGHT),
    TRY_TO_DOUBLE(CASH_WEIGHT),
    TRY_TO_DOUBLE(OTIF_DELTA_PCT),
    TRY_TO_DOUBLE(LEAD_TIME_DELTA_DAYS),
    TRY_TO_DOUBLE(SAFETY_STOCK_DELTA_PCT),
    TRY_TO_DOUBLE(PIPELINE_STOCK_DELTA_PCT),
    TRY_TO_DOUBLE(ROCE_DELTA_PCT),
    TRY_TO_DOUBLE(FCF_DELTA_PCT),
    PERMISSIBLE_RED,
    MANDATORY_GREEN,
    ECONOMIC_BET
FROM RAW.SCENARIO_CONTROL_STAGE;

INSERT INTO ATOMIC.CAUSAL_TRACE_DEFINITION (
    SOURCE_METRIC, TARGET_METRIC, RELATIONSHIP_TYPE,
    CAUSAL_WEIGHT, DESCRIPTION, EXAMPLE_SCENARIO
)
SELECT 
    SOURCE_METRIC,
    TARGET_METRIC,
    RELATIONSHIP_TYPE,
    TRY_TO_DOUBLE(CAUSAL_WEIGHT),
    DESCRIPTION,
    EXAMPLE_SCENARIO
FROM RAW.CAUSAL_TRACE_STAGE;

INSERT INTO ATOMIC.ML_MODEL_REGISTRY (
    MODEL_NAME, MODEL_VERSION, TARGET_VARIABLE,
    FEATURE_SET, TRAINING_DATE, VALIDATION_METRICS, IS_ACTIVE
)
SELECT 
    MODEL_NAME,
    MODEL_VERSION,
    TARGET_VARIABLE,
    TRY_PARSE_JSON(FEATURE_SET),
    TRY_TO_DATE(TRAINING_DATE),
    TRY_PARSE_JSON(VALIDATION_METRICS),
    TRY_TO_BOOLEAN(IS_ACTIVE)
FROM RAW.ML_MODEL_REGISTRY_STAGE;

-- =============================================================================
-- STEP 4: Populate DATA MART (STRATEGY_SIMULATOR) - denormalized aggregates
-- =============================================================================

INSERT INTO STRATEGY_SIMULATOR.FACT_PERFORMANCE_SNAPSHOT (
    PERFORMANCE_MONTH, REGION, STRATEGY_MODE,
    OTIF_PCT, FILL_RATE_PCT, NET_SALES_GROWTH_PCT, LEAD_TIME_DAYS,
    ORDER_FLEXIBILITY_SCORE, FORECAST_MAPE_PCT, FORECAST_BIAS_PCT, NPI_COUNT,
    GROSS_MARGIN_PCT, EBITDA_MARGIN_PCT, COGS_USD, SGA_USD,
    OEE_PCT, FIRST_PASS_YIELD_PCT, PURCHASING_PRICE_INDEX,
    ROCE_PCT, FREE_CASH_FLOW_USD, CASH_CONVERSION_CYCLE_DAYS,
    DIOH_DAYS, DSO_DAYS, DPO_DAYS, ASSET_TURNS,
    CYCLE_STOCK_VALUE, SAFETY_STOCK_VALUE, PIPELINE_STOCK_VALUE,
    ANTICIPATION_STOCK_VALUE, STRATEGIC_STOCK_VALUE, TOTAL_INVENTORY_VALUE,
    NOPAT_USD, WORKING_CAPITAL_DELTA_USD, FIXED_ASSET_DELTA_USD,
    CAPITAL_EMPLOYED_USD, EVA_USD
)
SELECT 
    TRY_TO_DATE(PERFORMANCE_MONTH),
    REGION,
    STRATEGY_MODE,
    TRY_TO_DOUBLE(OTIF_PCT),
    TRY_TO_DOUBLE(FILL_RATE_PCT),
    TRY_TO_DOUBLE(NET_SALES_GROWTH_PCT),
    TRY_TO_DOUBLE(LEAD_TIME_DAYS),
    TRY_TO_DOUBLE(ORDER_FLEXIBILITY_SCORE),
    TRY_TO_DOUBLE(FORECAST_MAPE_PCT),
    TRY_TO_DOUBLE(FORECAST_BIAS_PCT),
    TRY_TO_NUMBER(NPI_COUNT),
    TRY_TO_DOUBLE(GROSS_MARGIN_PCT),
    TRY_TO_DOUBLE(EBITDA_MARGIN_PCT),
    TRY_TO_DOUBLE(COGS_USD),
    TRY_TO_DOUBLE(SGA_USD),
    TRY_TO_DOUBLE(OEE_PCT),
    TRY_TO_DOUBLE(FIRST_PASS_YIELD_PCT),
    TRY_TO_DOUBLE(PURCHASING_PRICE_INDEX),
    TRY_TO_DOUBLE(ROCE_PCT),
    TRY_TO_DOUBLE(FREE_CASH_FLOW_USD),
    TRY_TO_DOUBLE(CASH_CONVERSION_CYCLE_DAYS),
    TRY_TO_DOUBLE(DIOH_DAYS),
    TRY_TO_DOUBLE(DSO_DAYS),
    TRY_TO_DOUBLE(DPO_DAYS),
    TRY_TO_DOUBLE(ASSET_TURNS),
    TRY_TO_DOUBLE(CYCLE_STOCK_VALUE),
    TRY_TO_DOUBLE(SAFETY_STOCK_VALUE),
    TRY_TO_DOUBLE(PIPELINE_STOCK_VALUE),
    TRY_TO_DOUBLE(ANTICIPATION_STOCK_VALUE),
    TRY_TO_DOUBLE(STRATEGIC_STOCK_VALUE),
    TRY_TO_DOUBLE(TOTAL_INVENTORY_VALUE),
    TRY_TO_DOUBLE(NOPAT_USD),
    TRY_TO_DOUBLE(WORKING_CAPITAL_DELTA_USD),
    TRY_TO_DOUBLE(FIXED_ASSET_DELTA_USD),
    TRY_TO_DOUBLE(CAPITAL_EMPLOYED_USD),
    TRY_TO_DOUBLE(EVA_USD)
FROM RAW.PERFORMANCE_SNAPSHOT_STAGE;

INSERT INTO STRATEGY_SIMULATOR.PREDICTIVE_BRIDGE (
    PERFORMANCE_MONTH, REGION, SCENARIO_ID,
    PREDICTED_FCF_USD, PREDICTED_ROCE_PCT, PREDICTED_SAFETY_STOCK_USD, PREDICTED_PIPELINE_STOCK_USD,
    LEAD_TIME_IMPACT_FCF, FORECAST_ERROR_IMPACT_SAFETY, BATCH_SIZE_IMPACT_CYCLE,
    FCF_LOWER_BOUND, FCF_UPPER_BOUND, ROCE_LOWER_BOUND, ROCE_UPPER_BOUND, MODEL_SOURCE
)
SELECT 
    TRY_TO_DATE(r.PERFORMANCE_MONTH),
    r.REGION,
    s.SCENARIO_ID,
    TRY_TO_DOUBLE(r.PREDICTED_FCF_USD),
    TRY_TO_DOUBLE(r.PREDICTED_ROCE_PCT),
    TRY_TO_DOUBLE(r.PREDICTED_SAFETY_STOCK_USD),
    TRY_TO_DOUBLE(r.PREDICTED_PIPELINE_STOCK_USD),
    TRY_TO_DOUBLE(r.LEAD_TIME_IMPACT_FCF),
    TRY_TO_DOUBLE(r.FORECAST_ERROR_IMPACT_SAFETY),
    TRY_TO_DOUBLE(r.BATCH_SIZE_IMPACT_CYCLE),
    TRY_TO_DOUBLE(r.FCF_LOWER_BOUND),
    TRY_TO_DOUBLE(r.FCF_UPPER_BOUND),
    TRY_TO_DOUBLE(r.ROCE_LOWER_BOUND),
    TRY_TO_DOUBLE(r.ROCE_UPPER_BOUND),
    r.MODEL_SOURCE
FROM RAW.PREDICTIVE_BRIDGE_STAGE r
LEFT JOIN ATOMIC.SCENARIO_CONTROL s ON TRY_TO_NUMBER(r.SCENARIO_ID) = s.SCENARIO_ID;
