CREATE CORTEX SEARCH SERVICE STRATEGY_SIMULATOR.SUPPLY_CHAIN_CONTEXT_SEARCH
ON CONTENT_TEXT
ATTRIBUTES DOC_NAME, DOC_TYPE, QUARTER, YEAR
WAREHOUSE = CAUSAL_CHAIN_WH
TARGET_LAG = '1 hour'
AS (
  SELECT 
    DOC_ID,
    CONTENT_TEXT,
    DOC_NAME,
    DOC_TYPE,
    QUARTER,
    YEAR
  FROM RAW.QBR_DOCUMENTS
);
